// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5l2q8iglqbNelb3PQz4zWBuqWc1JoOOU',
    appId: '1:615541656284:web:fa25f1e31adf38865cc219',
    messagingSenderId: '615541656284',
    projectId: 'flutter-easy-f91e8',
    authDomain: 'flutter-easy-f91e8.firebaseapp.com',
    storageBucket: 'flutter-easy-f91e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZyPIoT9kEbHK1q-DRDSxZV4ZqUO7ltWY',
    appId: '1:615541656284:android:e3589e8cb97b419b5cc219',
    messagingSenderId: '615541656284',
    projectId: 'flutter-easy-f91e8',
    storageBucket: 'flutter-easy-f91e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Dd1Q6rk_s3QbFwDKdvhpSXYf5RdXpS8',
    appId: '1:615541656284:ios:19d012dea6f138e35cc219',
    messagingSenderId: '615541656284',
    projectId: 'flutter-easy-f91e8',
    storageBucket: 'flutter-easy-f91e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractice1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Dd1Q6rk_s3QbFwDKdvhpSXYf5RdXpS8',
    appId: '1:615541656284:ios:19d012dea6f138e35cc219',
    messagingSenderId: '615541656284',
    projectId: 'flutter-easy-f91e8',
    storageBucket: 'flutter-easy-f91e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractice1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5l2q8iglqbNelb3PQz4zWBuqWc1JoOOU',
    appId: '1:615541656284:web:6d6fb2a7328ce8645cc219',
    messagingSenderId: '615541656284',
    projectId: 'flutter-easy-f91e8',
    authDomain: 'flutter-easy-f91e8.firebaseapp.com',
    storageBucket: 'flutter-easy-f91e8.firebasestorage.app',
  );

}